ARG PHP_VERSION
ARG XDEBUG_VERSION=xdebug

FROM uogsoe/soe-php-apache:${PHP_VERSION}

RUN pecl install ${XDEBUG_VERSION}
RUN docker-php-ext-enable xdebug

RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
RUN chmod +x /usr/local/bin/composer
RUN composer global require hirak/prestissimo

EXPOSE 80
